//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCv.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Education
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "Bu Alan Boþ Geçilemez.")]
        public string Title { get; set; }
        [Required(ErrorMessage = "Bu Alan Boþ Geçilemez.")]
        public string SubTitle { get; set; }
        public string SubTitle2 { get; set; }
        [Required(ErrorMessage = "Bu Alan Boþ Geçilemez.")]
        [StringLength(10, ErrorMessage = "Lütfen En Fazla 10 Karakter Giriniz")]
        public string GPA { get; set; }
        [Required(ErrorMessage = "Bu Alan Boþ Geçilemez.")]
        public string Date { get; set; }
    }
}
