//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCv.Models.Entity
{
    using System;
    using System.ComponentModel.DataAnnotations;

    public partial class Talent
    {
        public int ID { get; set; }
        public string TalentName { get; set; }
        public Nullable<byte> TalentPercent { get; set; }
    }
}
